"""empty message

Revision ID: 88599e0872b1
Revises: bc6939a01432
Create Date: 2018-05-30 10:38:19.974396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88599e0872b1'
down_revision = 'bc6939a01432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataNascimento', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=50), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    # ### end Alembic commands ###
