"""empty message

Revision ID: f43d7689b9ef
Revises: 
Create Date: 2018-06-11 11:33:09.625297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43d7689b9ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataNascimento', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=50), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    op.drop_table('users')
    # ### end Alembic commands ###
